name: new_nokhbegun
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/white.png
    - assets/black.png

  fonts:
  - family: IranSans
    fonts:
      - asset: assets/fonts/IranSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/IranSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/IranSans-Bold.ttf
        weight: 700
